services:
  - type: web
    name: rifa-facil-app
    env: static
    region: ohio
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
